增加对网易云音乐.uc缓存格式和QQ音乐.cache缓存格式的支持
unlock-music/unlock-music pull request #161
Opened 2021-06-01 05:45 UTC by qq1010903229

增加对网易云音乐.uc缓存格式和QQ音乐.cache缓存格式的支持

2021-06-01 05:47 UTC, qq1010903229 commented
[网易云缓存uc文件样本.zip](https://github.com/unlock-music/unlock-music/files/6573660/uc.zip)
压缩包密码34

2021-06-01 05:48 UTC, qq1010903229 commented
[QQ音乐缓存cache文件样本.zip](https://github.com/unlock-music/unlock-music/files/6573666/QQ.cache.zip)

2021-06-01 23:14 UTC, emmmx commented
It seems doesn't work on QQ music cache files for encrypted files.
You may try to call QMCDecrypt to handle such cases
[sample(.mgg.cache).zip](https://github.com/unlock-music/unlock-music/files/6581020/sample.mgg.cache.zip)

2021-06-02 00:07 UTC, emmmx requested changes
Great job, but fix the following problem please.

2021-06-02 00:07 UTC, emmmx commented on src/decrypt/qmccache.ts
> +        ext = SniffAudioExt(buffer, raw_ext);
Need to handle cases like .mgg.cache

2021-06-02 00:07 UTC, emmmx commented on src/decrypt/common.ts
> +            rt_data = await NcmCacheDecrypt(file.raw, raw_filename, "mp3");
Do not use "mp3" as raw_ext, it caused the conversion to fail.

```golang
rt_data = await NcmCacheDecrypt(file.raw, raw_filename, raw_ext);
```

2021-06-03 05:00 UTC, emmmx commented
Thanks for your work.
Right now it's still not working. I will merge to a non-main branch and fix.
Since your commit is too fragmented, I would squash and merge

2021-06-03 05:00 UTC, merged